"""empty message

Revision ID: 1b41a2e982a8
Revises: 8c4ff6d0699d
Create Date: 2018-05-08 21:28:39.259781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b41a2e982a8'
down_revision = '8c4ff6d0699d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('match_outcome')
        batch_op.drop_column('win_bool')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win_bool', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('match_outcome', sa.VARCHAR(length=4), nullable=True))

    # ### end Alembic commands ###
