"""empty message

Revision ID: 8c4ff6d0699d
Revises: 324d51052f07
Create Date: 2018-05-08 21:01:26.478390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4ff6d0699d'
down_revision = '324d51052f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('win_bool', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'win_bool')
    # ### end Alembic commands ###
