"""added match outcome in db

Revision ID: d2e392e54485
Revises: 1b41a2e982a8
Create Date: 2018-05-08 21:29:31.142744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e392e54485'
down_revision = '1b41a2e982a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_outcome', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('match_outcome')

    # ### end Alembic commands ###
